### ISSUE TITLE
Possibly redundant AdvertisementPatch parameter in ExpireAsync

### ISSUE THREAD

**Issue by brettmas** [SEEK-Jobs/ad-posting-api-client#1]
What is the purpose of the AdvertisementPatch parameter in the AdPostingApiClient.ExpireAsync method? 
It only seems to allow patching the ad to 'Expired' or 'Open', I would have thought that 'Expired' would be implied by the 'ExpireAsync' method name.
Maybe I'm misunderstanding the call, is there any reason we would Expire an ad setting the 'Open' state?

**Comment by ConradLang** [comment]
We've already removed that parameter on our internal code base and will publish the change soon. Thanks for reporting this.

**Comment by ConradLang** [comment]
Fixed in 441fd9a15fc9cddeae6c9cd7e899b42f32169f05. We're following [RFC-6902](https://tools.ietf.org/html/rfc6902) for the patch request content (only patching the advertisement status to "Expired" is currently supported).
