### ISSUE TITLE
Advertisement.State doesn't seem to get assigned when calling GetAdvertisementAsync

### ISSUE THREAD

**Issue by brettmas** [SEEK-Jobs/ad-posting-api-client#2]
Advertisement.State doesn't get assigned when calling GetAdvertisementAsync, we're unable to distinguish between "Open" and "Expired" ads, and a 0 (zero) value is assigned which is invalid for this Enum.

**Comment by ConradLang** [comment]
Thanks for reporting this. We've fixed this bug and once tested, we'll publish an updated client.

**Comment by ConradLang** [comment]
Fixed in 441fd9a15fc9cddeae6c9cd7e899b42f32169f05 - _This was a server issue where we were not setting the state on GET._
